### ISSUE TITLE
Create an UI admin feature to allow managing in retry messages

### ISSUE THREAD

**Issue by rodrigobelo** [Farfetch/kafka-flow-retry-extensions#32]
FEATURES
- List of in retry messages - #112 
- Cancellation of messages - #113 
- Enqueue messages manually - #114, #115
- Authentication/Authorization - #116
- TTL configuration - #117 
- Maximum number of retries - #118
- Download messages in allowed cases (PCI, scopes, and permission) - #119, #120
- Metrics such as total messages in retry, how many times was retried, last TTL execution - #122 

PHASES
- UX Design for each feature
- Identify technical points of extension of the current KafkaFlow dashboard
- Development

**Comment by luispfgarces** [comment]
Issue is being split into several issues (in progress).

Created so far:
- #112
- #113

**Comment by luispfgarces** [comment]
We have split this issue into several issues (noted in the description). Closing this issue as it no longer makes sense.
